kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ghost-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
