kind: PersistentVolume
apiVersion: v1
metadata:
  name: ghost-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/cychong/Dropbox/Apps/ghost/content"
